import { StyleSheet } from "react-native";

export const movieStyles = StyleSheet.create({
  providerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  providerLabel: {
    color: '#9ca3af',
    fontSize: 13,
    width: 50,
  },
  providerIcons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  providerLogo: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#1a1a2e',
  },
  container: {
    flex: 1,
    backgroundColor: "#0f0f0f",
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: "#0f0f0f",
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: {
    color: "#ff4444",
    fontSize: 16,
  },
  backButton: {
    position: "absolute",
    left: 16,
    zIndex: 10,
    width: 40,
    height: 40,
  },
  backButtonInner: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  backdropContainer: {
    height: 220,
    position: "relative",
  },
  backdrop: {
    width: "100%",
    height: "100%",
  },
  backdropPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#1a1a2e",
    alignItems: "center",
    justifyContent: "center",
  },
  backdropGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 120,
  },
  infoRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginTop: -60,
    marginBottom: 16,
  },
  poster: {
    width: 100,
    height: 150,
    borderRadius: 8,
    backgroundColor: "#1a1a2e",
  },
  posterPlaceholder: {
    width: 100,
    height: 150,
    borderRadius: 8,
    backgroundColor: "#1a1a2e",
    alignItems: "center",
    justifyContent: "center",
  },
  infoText: {
    flex: 1,
    paddingLeft: 12,
    paddingTop: 60,
    justifyContent: "flex-end",
  },
  title: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  meta: {
    color: "#9ca3af",
    fontSize: 13,
  },
  rating: {
    color: "#fbbf24",
    fontSize: 13,
  },
  status: {
    color: "#9ca3af",
    fontSize: 12,
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  genreRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 20,
  },
  genreChip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "rgba(229,9,20,0.15)",
    borderWidth: 1,
    borderColor: "rgba(229,9,20,0.3)",
  },
  genreText: {
    color: "#E50914",
    fontSize: 12,
    fontWeight: "600",
  },
  section: {
    marginBottom: 24,
  },
  directorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 6,
  },
  sectionTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
  },
  overview: {
    color: "#9ca3af",
    fontSize: 14,
    lineHeight: 22,
  },
  directorName: {
    color: "#9ca3af",
    fontSize: 14,
  },
  castCard: {
    width: 80,
    marginRight: 12,
  },
  castImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#1a1a2e",
    marginBottom: 6,
  },
  castImagePlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#1a1a2e",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  castName: {
    color: "white",
    fontSize: 11,
    textAlign: "center",
    fontWeight: "600",
  },
  castCharacter: {
    color: "#9ca3af",
    fontSize: 10,
    textAlign: "center",
    marginTop: 2,
  },
  userReviewCard: {
    backgroundColor: "rgba(229,9,20,0.08)",
    borderWidth: 1,
    borderColor: "rgba(229,9,20,0.2)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  reviewCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 10,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  reviewUsername: {
    color: "white",
    fontWeight: "600",
    fontSize: 13,
  },
  reviewForm: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 24,
  },
  reviewInput: {
    backgroundColor: "rgba(255,255,255,0.07)",
    color: "white",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    padding: 12,
    minHeight: 80,
    textAlignVertical: "top",
    fontSize: 14,
  },
  submitButton: {
    backgroundColor: "#E50914",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  submitButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
});
