import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  changePasswordButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 12,
    padding: 16,
    gap: 8,
    marginBottom: 12,
  },
  changePasswordText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "flex-end",
  },
  modalBox: {
    backgroundColor: "#1a1a2e",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  modalLabel: {
    color: "#9ca3af",
    fontSize: 13,
    marginBottom: 6,
    marginTop: 12,
  },
  modalInput: {
    backgroundColor: "rgba(255,255,255,0.07)",
    color: "white",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    padding: 12,
    fontSize: 14,
  },
  modalError: {
    backgroundColor: "rgba(255,68,68,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,68,68,0.3)",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  modalErrorText: {
    color: "#ff4444",
    fontSize: 13,
    textAlign: "center",
  },
  modalButton: {
    backgroundColor: "#E50914",
    borderRadius: 10,
    padding: 14,
    alignItems: "center",
    marginTop: 20,
  },
  modalButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 15,
  },
  successContainer: {
    alignItems: "center",
    paddingVertical: 24,
    gap: 12,
  },
  successText: {
    color: "#22c55e",
    fontSize: 18,
    fontWeight: "bold",
  },

  email: {
    color: "#9ca3af",
    fontSize: 14,
    marginTop: 4,
  },
  username: {
    color: "white",
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 12,
  },
  container: {
    flex: 1,
    backgroundColor: "#0f0f0f",
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: "#0f0f0f",
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  avatarSection: {
    alignItems: "center",
    paddingVertical: 32,
  },
  statsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 32,
  },
  statCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    width: "47%",
  },
  statNumber: {
    color: "white",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 4,
  },
  statLabel: {
    color: "#9ca3af",
    fontSize: 13,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(229,9,20,0.1)",
    borderWidth: 1,
    borderColor: "rgba(229,9,20,0.3)",
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  logoutText: {
    color: "#E50914",
    fontSize: 16,
    fontWeight: "600",
  },
});
